"""
Step 8 — Snippet-Based HTML Renderer
Reads a subagent-produced JSON containing slide content data (type + vars),
loads the matching snippet template for each slide type, substitutes {{VAR}}
placeholders, wraps each snippet in the required section/slide-item scaffold,
then assembles a full HTML page using CSS + script from the master template.

This approach is deterministic: the HTML structure is always correct because
it is built from canonical snippet files, not generated by a model.

Usage (run from project root):
    python3 Carousels/scripts/step8_renderer.py --input /tmp/carousel_{uuid}.json [--batch 1]

Input JSON (written by subagent):
    {
      "uuid": "...",
      "running_no": N,
      "folder_name": "N_uuid",
      "slide_count": N,
      "page_title": "Hook Headline Here — DadFit Carousel",
      "slides": [
        {
          "type": "A1",
          "slide_no": 1,
          "label": "Cover",
          "vars": {
            "HEADLINE": "THE 5-MINUTE<br>DAD <span style='color:#34C363;'>RESET</span>",
            "SUBTEXT": "How Indian dads can reclaim energy in 30 days.",
            "DOODLE_ALT": "A stopwatch with a green checkmark"
          }
        },
        ...
      ],
      "doodle_prompts": [
        {"running_no": N, "image_name": "N-d-01.png", "prompt": "..."},
        ...
      ]
    }

Auto-injected vars (do NOT include in subagent JSON — renderer computes them):
    COUNTER    → "01 / 10" format (zero-padded slide_no / total slide_count)
    DOODLE_SRC → "../doodles/{running_no}-d-{slide_no:02d}.png"
    LOGO_SRC   → "../../../../Resources/Images/logo.png"

Output:
    - Writes carousel.html to Carousels/data/batch_{N}/{folder_name}/carousel.html
    - Prints a result JSON line to stdout (for the main agent to collect)
"""
import json, os, re, argparse, sys

# ── Slide type → human label (shown in section-header and slide-label) ──────
SLIDE_TYPE_LABELS = {
    'A1': 'Cover — Hook',
    'A2': 'Cover — Hook + Photo',
    'A3': 'Cover — Full-Bleed Photo',
    'A4': 'Cover — Caveat Hook',
    'A5': 'Cover — Challenge',
    'B1': 'Content — Tip',
    'B2': 'Content — Tip + Photo',
    'B3': 'Content — Full-Bleed Photo',
    'B4': 'Content — Callout',
    'B5': 'Content — Wrong vs Right',
    'B6': 'Content — 3-Step Process',
    'C1': 'Problem — Pain',
    'C2': 'Problem — Pain + Photo',
    'C3': 'Problem — Myth vs Truth',
    'C4': 'Problem — Excuses',
    'D1': 'Proof — Stat',
    'D2': 'Proof — Stat + Photo',
    'D3': 'Proof — Two Stats',
    'D4': 'Proof — Progress Bars',
    'E1': 'Bridge — Minimal',
    'E2': 'Bridge — Section Label',
    'E3': 'Bridge — Green Quote',
    'E4': 'Bridge — Part Pills',
    'F1': 'Pattern Break — Full-Bleed Image',
    'F2': 'Pattern Break — Bold Statement',
    'F3': 'Pattern Break — Caveat Poster',
    'F4': 'Pattern Break — Rule Break',
    'G1': 'Recap — Numbered List',
    'G2': 'Recap — Icon Grid',
    'G3': 'Recap — One-Line Truth',
    'G4': 'Recap — Habit Scoreboard',
    'H1': 'CTA — Text Only',
    'H2': 'CTA — Founder Photo',
    'H3': 'CTA — DM Action',
    'H4': 'CTA — Testimonial',
}

LOGO_SRC    = '../../../../Resources/Images/logo.png'
SNIPPETS_DIR = 'Carousels/templates/design 1/snippets'
TEMPLATE_PATH = 'Carousels/templates/design 1/DadFit Carousel Templates.html'
FONT_LINK = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">\n'
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
    '  <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700'
    '&family=Inter:wght@400;500;600;700;800&family=Permanent+Marker&display=swap" rel="stylesheet">'
)

# ── Args ─────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser()
parser.add_argument('--input', required=True, help='Path to subagent JSON file')
parser.add_argument('--batch', type=int, default=1)
args = parser.parse_args()
BATCH_NO = args.batch

# ── Load input ───────────────────────────────────────────────────────────────
if not os.path.exists(args.input):
    print(f'ERROR: Input file not found: {args.input}', file=sys.stderr)
    sys.exit(1)

with open(args.input, encoding='utf-8') as f:
    data = json.load(f)

uuid            = data['uuid']
running_no      = data['running_no']
folder_name     = data['folder_name']
slide_count     = data['slide_count']
page_title      = data.get('page_title', f'Carousel {running_no} — DadFit')
slides          = data['slides']
doodle_prompts  = data.get('doodle_prompts', [])

# ── Load master template for CSS + Script ────────────────────────────────────
with open(TEMPLATE_PATH, encoding='utf-8') as f:
    template = f.read()

style_start = template.index('<style>')
style_end   = template.index('</style>') + len('</style>')
style_block = template[style_start:style_end]

script_start = template.rindex('<script>')
script_end   = template.rindex('</script>') + len('</script>')
script_block = template[script_start:script_end]


# ── Snippet helpers ──────────────────────────────────────────────────────────

def load_snippet(slide_type: str) -> str:
    path = os.path.join(SNIPPETS_DIR, f'{slide_type}.html')
    if not os.path.exists(path):
        raise FileNotFoundError(f'Snippet not found: {path}')
    with open(path, encoding='utf-8') as f:
        return f.read()


def substitute_vars(snippet: str, vars_map: dict) -> str:
    """Replace {{KEY}} placeholders with values from vars_map."""
    def replacer(m):
        key = m.group(1)
        if key in vars_map:
            return str(vars_map[key])
        # Leave unresolved placeholders visible for debugging
        return f'[MISSING:{key}]'
    return re.sub(r'\{\{([A-Z0-9_]+)\}\}', replacer, snippet)


def resolve_conditionals(html: str, vars_map: dict) -> str:
    """Handle {{#if VAR}}...{{/if}} blocks — include block only if VAR has a truthy value."""
    def cond_replacer(m):
        key = m.group(1)
        content = m.group(2)
        return content if vars_map.get(key) else ''
    return re.sub(r'\{\{#if ([A-Z0-9_]+)\}\}(.*?)\{\{/if\}\}', cond_replacer, html, flags=re.DOTALL)


def expand_habit_dots(html: str) -> str:
    """Convert data-filled="N" on habit dot containers into actual dot divs.
    
    The G4 snippet uses:
      <div style="display:flex;gap:10px;" data-filled="{{HABIT1_FILLED}}">
      </div>
    
    After var substitution, data-filled holds an integer (0–7). This function
    replaces those containers with 7 filled/empty dot squares.
    """
    def dot_replacer(m):
        attrs_before = m.group(1)
        filled = int(m.group(2)) if m.group(2).isdigit() else 0
        dots = ''
        for i in range(7):
            if i < filled:
                dots += '<div style="width:28px;height:28px;border-radius:4px;background:#34C363;"></div>'
            else:
                dots += '<div style="width:28px;height:28px;border-radius:4px;border:2px solid #444;"></div>'
        return f'<div {attrs_before}>{dots}</div>'
    return re.sub(
        r'<div (style="display:flex;gap:10px;") data-filled="(\d+)">\s*</div>',
        dot_replacer,
        html
    )


def render_slide(slide: dict, total: int, batch_no: int) -> str:
    """Load snippet, substitute all vars, wrap in section scaffold."""
    slide_type  = slide['type']
    slide_no    = slide['slide_no']
    label       = slide.get('label', SLIDE_TYPE_LABELS.get(slide_type, slide_type))
    vars_map    = dict(slide.get('vars', {}))

    # Auto-inject computed vars
    vars_map.setdefault('COUNTER',    f'{slide_no:02d} / {total:02d}')
    vars_map.setdefault('DOODLE_SRC', f'../doodles/{running_no}-d-{slide_no:02d}.png')
    vars_map.setdefault('LOGO_SRC',   LOGO_SRC)

    # Load and process snippet
    snippet = load_snippet(slide_type)
    snippet = resolve_conditionals(snippet, vars_map)
    snippet = substitute_vars(snippet, vars_map)
    snippet = expand_habit_dots(snippet)

    # Build type label for headers
    type_label = SLIDE_TYPE_LABELS.get(slide_type, slide_type)

    # Wrap in section scaffold
    return (
        f'<div class="section">\n'
        f'  <div class="section-header"><h2>Slide {slide_no} — {slide_type} — {label}</h2></div>\n'
        f'  <div class="slides-grid">\n'
        f'    <div class="slide-item">\n'
        f'      <div class="slide-label"><strong>{slide_type}</strong> — {label}</div>\n'
        f'      <div class="slide-wrapper">\n'
        f'        <div class="slide">\n'
        f'{snippet}\n'
        f'        </div>\n'
        f'      </div>\n'
        f'    </div>\n'
        f'  </div>\n'
        f'</div>'
    )


# ── Render all slides ────────────────────────────────────────────────────────
errors = []
rendered_slides = []

for slide in slides:
    try:
        rendered_slides.append(render_slide(slide, slide_count, BATCH_NO))
    except FileNotFoundError as e:
        errors.append(str(e))
    except Exception as e:
        errors.append(f'Slide {slide.get("slide_no","?")} ({slide.get("type","?")}): {e}')

if errors:
    print('RENDER ERRORS:', file=sys.stderr)
    for e in errors:
        print(f'  ✗ {e}', file=sys.stderr)
    result_err = {
        'uuid': uuid, 'running_no': running_no,
        'status': 'RENDER_FAILED', 'errors': errors
    }
    print(json.dumps(result_err))
    sys.exit(2)

slides_html = '\n\n'.join(rendered_slides)

# ── Validate output (belt-and-suspenders) ───────────────────────────────────
def _validate(html: str) -> list[str]:
    n_sections = html.count('<div class="section">')
    n_headers  = html.count('class="section-header">')
    n_labels   = html.count('class="slide-label"')
    errs = []
    if n_sections == 0:
        errs.append('No <div class="section"> blocks found')
    if n_headers < n_sections:
        errs.append(f'Missing section-header: {n_headers} vs {n_sections} sections')
    if n_labels < n_sections:
        errs.append(f'Missing slide-label: {n_labels} vs {n_sections} sections')
    if '[MISSING:' in html:
        missing = re.findall(r'\[MISSING:([A-Z0-9_]+)\]', html)
        errs.append(f'Unresolved placeholders: {", ".join(set(missing))}')
    return errs

validation_errors = _validate(slides_html)
if validation_errors:
    print('VALIDATION FAILED:', file=sys.stderr)
    for e in validation_errors:
        print(f'  ✗ {e}', file=sys.stderr)
    result_err = {
        'uuid': uuid, 'running_no': running_no,
        'status': 'VALIDATION_FAILED', 'errors': validation_errors
    }
    print(json.dumps(result_err))
    sys.exit(2)

# ── Build output folder ──────────────────────────────────────────────────────
out_dir  = f'Carousels/data/batch_{BATCH_NO}/{folder_name}'
out_path = f'{out_dir}/carousel.html'
os.makedirs(out_dir, exist_ok=True)

# ── Assemble full HTML page ──────────────────────────────────────────────────
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{page_title}</title>
  {FONT_LINK}
  {style_block}
</head>
<body>

<h1 class="page-title">{page_title}</h1>
<p class="page-subtitle">{slide_count} slides · DadFit · Batch {BATCH_NO}</p>

{slides_html}

{script_block}
</body>
</html>"""

with open(out_path, 'w', encoding='utf-8') as f:
    f.write(html)

file_size = os.path.getsize(out_path)
print(f'Written: {out_path} ({file_size // 1024}KB, {slide_count} slides)', file=sys.stderr)

# ── Result JSON for main agent ───────────────────────────────────────────────
result = {
    'uuid': uuid,
    'running_no': running_no,
    'folder_name': folder_name,
    'slide_count': slide_count,
    'html_path': out_path,
    'doodle_prompts': doodle_prompts
}
print(json.dumps(result))
