"""
step1_topic_fetcher.py
Inserts topics generated by the Step 1 agent into the Carousel DB.

The agent (via SKILL.md) generates topics and saves them to topics.json.
This script validates and inserts that file into the DB.

Usage:
  python3 scripts/step1_topic_fetcher.py --batch 1 --topics-file data/batch_1/topics.json
  python3 scripts/step1_topic_fetcher.py --batch 1 --topics-file data/batch_1/topics.json --dry-run
"""

import sqlite3
import uuid
import os
import json
import argparse

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "db.sqlite")

REQUIRED_FIELDS = {"title", "keyword", "trait", "subniche", "category"}
VALID_CATEGORIES = {"Diet & Workout", "Lifestyle", "Financial"}


def validate(topics):
    errors = []

    for i, t in enumerate(topics):
        missing = REQUIRED_FIELDS - set(t.keys())
        if missing:
            errors.append("  Topic %d: missing fields %s" % (i + 1, missing))
        if t.get("category") not in VALID_CATEGORIES:
            errors.append("  Topic %d: invalid category '%s'" % (i + 1, t.get("category")))

    if len(topics) != 100:
        errors.append("  Expected 100 topics, got %d" % len(topics))

    seen = set()
    for t in topics:
        key = t.get("title", "").lower()
        if key in seen:
            errors.append("  Duplicate title: %s" % t.get("title"))
        seen.add(key)

    dist = {}
    for t in topics:
        cat = t.get("category")
        dist[cat] = dist.get(cat, 0) + 1

    dw = dist.get("Diet & Workout", 0)
    ls = dist.get("Lifestyle", 0)
    fi = dist.get("Financial", 0)

    if not (65 <= dw <= 75):
        errors.append("  Diet & Workout count is %d — expected 65-75" % dw)
    if not (17 <= ls <= 23):
        errors.append("  Lifestyle count is %d — expected 17-23" % ls)
    if not (7 <= fi <= 13):
        errors.append("  Financial count is %d — expected 7-13" % fi)

    return errors


def run(batch_no, topics_file, dry_run):
    if not os.path.exists(topics_file):
        print("ERROR: file not found: %s" % topics_file)
        return

    with open(topics_file, "r", encoding="utf-8") as f:
        topics = json.load(f)

    print("\n  Loaded %d topics from %s" % (len(topics), topics_file))

    errors = validate(topics)
    if errors:
        print("\n  VALIDATION ERRORS:")
        for e in errors:
            print(e)
        print("\n  Fix topics.json and re-run.\n")
        return

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    # Check against the most recent completed batch (last 100 topics by batch_no)
    c.execute(
        "SELECT title FROM Carousel WHERE batch_no = (SELECT MAX(batch_no) FROM Carousel)"
    )
    prev_titles = {r["title"].lower() for r in c.fetchall()}

    dups = [t["title"] for t in topics if t["title"].lower() in prev_titles]
    if dups:
        print("\n  DUPLICATE TITLES found in previous batch (%d):" % len(dups))
        for d in dups:
            print("    - %s" % d)
        print("  Fix topics.json and re-run.\n")
        conn.close()
        return

    dist = {}
    subniche_dist = {}
    for t in topics:
        dist[t["category"]] = dist.get(t["category"], 0) + 1
        subniche_dist[t["subniche"]] = subniche_dist.get(t["subniche"], 0) + 1

    sep = "-" * 60
    print("\n%s\n  Topic Distribution -- Batch %d\n%s" % (sep, batch_no, sep))
    for cat, count in dist.items():
        print("  %-20s  %3d topics" % (cat, count))
    print(sep)
    for sub, count in sorted(subniche_dist.items()):
        print("    %-42s  %3d" % (sub, count))
    print("%s\n" % sep)

    if dry_run:
        print("  DRY RUN -- no changes made.\n")
        conn.close()
        return

    rows = [
        (str(uuid.uuid4()), batch_no, t["title"], t["keyword"], t["trait"])
        for t in topics
    ]

    try:
        c.execute("BEGIN")
        c.executemany(
            "INSERT INTO Carousel"
            " (uuid, batch_no, title, keyword, trait, current_stage, upload_status)"
            " VALUES (?, ?, ?, ?, ?, 'TOPIC_FETCHED', 'PENDING')",
            rows
        )
        conn.commit()
        print("  Inserted %d topics for batch %d\n" % (len(rows), batch_no))
    except Exception as e:
        conn.rollback()
        print("  ERROR: %s" % e)
        raise
    finally:
        conn.close()

    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        "SELECT COUNT(*) FROM Carousel WHERE batch_no = ? AND current_stage = 'TOPIC_FETCHED'",
        (batch_no,)
    )
    count = c.fetchone()[0]
    conn.close()
    print("  Verified: %d rows with batch_no=%d and current_stage=TOPIC_FETCHED\n" % (count, batch_no))


def main():
    p = argparse.ArgumentParser(description="Insert Step 1 topics into DB from topics.json")
    p.add_argument("--batch", type=int, required=True)
    p.add_argument("--topics-file", required=True)
    p.add_argument("--dry-run", action="store_true")
    a = p.parse_args()
    run(a.batch, a.topics_file, a.dry_run)


if __name__ == "__main__":
    main()
