"""
step4_hook_writer.py
Validates and inserts carousel hooks generated by the Step 4 agent.

Usage:
  python3 Carousels/scripts/step4_hook_writer.py --batch 1 --hooks-file Carousels/data/batch_1/hooks.json
  python3 Carousels/scripts/step4_hook_writer.py --batch 1 --hooks-file Carousels/data/batch_1/hooks.json --dry-run
"""

import sqlite3
import os
import json
import argparse

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "db.sqlite")

HOOK_MIN_WORDS = 5
HOOK_MAX_WORDS = 7


def _word_count(hook):
    return len(hook.strip().split())


def validate(entries, batch_uuids, prev_hooks):
    errors = []

    if len(entries) != 100:
        errors.append("  Expected 100 entries, got %d" % len(entries))

    seen_hooks = set()
    seen_uuids = set()

    for i, e in enumerate(entries):
        if "uuid" not in e or "hook" not in e:
            errors.append("  Entry %d: missing 'uuid' or 'hook'" % (i + 1))
            continue

        uid = e["uuid"]
        hook = e["hook"].strip()
        wc = _word_count(hook)

        if uid in seen_uuids:
            errors.append("  Duplicate UUID: %s" % uid)
        seen_uuids.add(uid)

        if uid not in batch_uuids:
            errors.append("  UUID not in batch: %s" % uid)

        if not (HOOK_MIN_WORDS <= wc <= HOOK_MAX_WORDS):
            errors.append(
                "  Hook word count %d (expected %d-%d): \"%s\"" % (
                    wc, HOOK_MIN_WORDS, HOOK_MAX_WORDS, hook,
                )
            )

        hook_lower = hook.lower()
        if hook_lower in seen_hooks:
            errors.append("  Duplicate hook within batch: \"%s\"" % hook)
        seen_hooks.add(hook_lower)

        if hook_lower in prev_hooks:
            errors.append("  Hook repeats previous batch: \"%s\"" % hook)

    return errors


def run(batch_no, hooks_file, dry_run):
    if not os.path.exists(hooks_file):
        print("ERROR: file not found: %s" % hooks_file)
        return

    with open(hooks_file, "r", encoding="utf-8") as f:
        entries = json.load(f)

    print("\n  Loaded %d entries from %s" % (len(entries), hooks_file))

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    batch_uuids = {
        r["uuid"]
        for r in conn.execute(
            "SELECT uuid FROM Carousel WHERE batch_no = ? AND current_stage = 'ORDER_SET'",
            (batch_no,),
        ).fetchall()
    }
    print("  Found %d ORDER_SET rows for batch %d" % (len(batch_uuids), batch_no))

    prev_hooks = {
        r["hook"].strip().lower()
        for r in conn.execute(
            "SELECT hook FROM Carousel WHERE batch_no < ? AND hook IS NOT NULL",
            (batch_no,),
        ).fetchall()
    }
    print("  Loaded %d previous batch hooks to check against" % len(prev_hooks))

    errors = validate(entries, batch_uuids, prev_hooks)
    if errors:
        print("\n  VALIDATION ERRORS (%d):" % len(errors))
        for e in errors:
            print(e)
        print("\n  Fix hooks.json and re-run.\n")
        conn.close()
        return

    sep = "-" * 72
    print("\n%s\n  Hook Preview — Batch %d\n%s" % (sep, batch_no, sep))

    # Build uuid -> running_no lookup for display
    rn_map = {
        r["uuid"]: r["running_no"]
        for r in conn.execute(
            "SELECT uuid, running_no FROM Carousel WHERE batch_no = ?", (batch_no,)
        ).fetchall()
    }
    sorted_entries = sorted(entries, key=lambda e: rn_map.get(e["uuid"], 9999))
    for e in sorted_entries:
        rn = rn_map.get(e["uuid"], "?")
        wc = _word_count(e["hook"])
        print("  #%-3s (%dw)  %s" % (rn, wc, e["hook"]))
    print(sep)

    if dry_run:
        print("\n  DRY RUN — no changes made.\n")
        conn.close()
        return

    try:
        conn.execute("BEGIN")
        for e in entries:
            conn.execute(
                "UPDATE Carousel SET hook = ?, current_stage = 'HOOK_WRITTEN' "
                "WHERE uuid = ? AND batch_no = ?",
                (e["hook"].strip(), e["uuid"], batch_no),
            )
        conn.commit()
        print("\n  Updated %d rows to HOOK_WRITTEN for batch %d\n" % (len(entries), batch_no))
    except Exception as exc:
        conn.rollback()
        print("  ERROR: %s" % exc)
        raise
    finally:
        conn.close()

    # Verify
    conn2 = sqlite3.connect(DB_PATH)
    n = conn2.execute(
        "SELECT COUNT(*) FROM Carousel WHERE batch_no = ? AND current_stage = 'HOOK_WRITTEN'",
        (batch_no,),
    ).fetchone()[0]
    conn2.close()
    print("  Verified: %d rows with current_stage = HOOK_WRITTEN\n" % n)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--batch", type=int, required=True)
    p.add_argument("--hooks-file", required=True)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    run(args.batch, args.hooks_file, args.dry_run)


if __name__ == "__main__":
    main()
