"""
step2_categorizer.py
Updates the Carousel DB with TOFU/MOFU/BOFU categories generated by the Step 2 agent.

The agent (via SKILL.md) produces categories.json; this script validates and applies it.

Usage:
  python3 scripts/step2_categorizer.py --batch 1 --categories-file data/batch_1/categories.json
  python3 scripts/step2_categorizer.py --batch 1 --categories-file data/batch_1/categories.json --dry-run
"""

import sqlite3
import os
import json
import argparse

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "db.sqlite")
VALID_CATEGORIES = {"TOFU", "MOFU", "BOFU"}


def validate(entries, batch_uuids):
    errors = []

    if len(entries) != 100:
        errors.append("  Expected 100 entries, got %d" % len(entries))

    seen = set()
    for i, e in enumerate(entries):
        if "uuid" not in e or "tofu_mofu_bofu" not in e:
            errors.append("  Entry %d: missing 'uuid' or 'tofu_mofu_bofu'" % (i + 1))
            continue
        if e["tofu_mofu_bofu"] not in VALID_CATEGORIES:
            errors.append("  Entry %d: invalid value '%s'" % (i + 1, e["tofu_mofu_bofu"]))
        if e["uuid"] in seen:
            errors.append("  Duplicate UUID: %s" % e["uuid"])
        seen.add(e["uuid"])
        if e["uuid"] not in batch_uuids:
            errors.append("  UUID not in batch: %s" % e["uuid"])

    dist = {}
    for e in entries:
        v = e.get("tofu_mofu_bofu", "")
        dist[v] = dist.get(v, 0) + 1

    for stage in VALID_CATEGORIES:
        pct = dist.get(stage, 0) / max(len(entries), 1) * 100
        if pct > 60:
            errors.append(
                "  %s is %.0f%% of topics — unusually high (>60%%). Check categorization." % (stage, pct)
            )

    return errors, dist


def run(batch_no, categories_file, dry_run):
    if not os.path.exists(categories_file):
        print("ERROR: file not found: %s" % categories_file)
        return

    with open(categories_file, "r", encoding="utf-8") as f:
        entries = json.load(f)

    print("\n  Loaded %d entries from %s" % (len(entries), categories_file))

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    c.execute(
        "SELECT uuid FROM Carousel WHERE batch_no = ? AND current_stage = 'TOPIC_FETCHED'",
        (batch_no,)
    )
    batch_uuids = {r["uuid"] for r in c.fetchall()}
    print("  Found %d TOPIC_FETCHED rows for batch %d" % (len(batch_uuids), batch_no))

    errors, dist = validate(entries, batch_uuids)
    if errors:
        print("\n  VALIDATION ERRORS:")
        for e in errors:
            print(e)
        print("\n  Fix categories.json and re-run.\n")
        conn.close()
        return

    sep = "-" * 60
    print("\n%s\n  Category Distribution -- Batch %d\n%s" % (sep, batch_no, sep))
    for stage in ["TOFU", "MOFU", "BOFU"]:
        count = dist.get(stage, 0)
        bar = "█" * (count // 2)
        print("  %-6s  %3d  %s" % (stage, count, bar))
    print("%s\n" % sep)

    if dry_run:
        print("  DRY RUN -- no changes made.\n")
        conn.close()
        return

    try:
        c.execute("BEGIN")
        for e in entries:
            c.execute(
                "UPDATE Carousel SET category = ?, current_stage = 'CATEGORIZED' "
                "WHERE uuid = ? AND batch_no = ?",
                (e["tofu_mofu_bofu"], e["uuid"], batch_no)
            )
        conn.commit()
        print("  Updated %d rows to CATEGORIZED for batch %d\n" % (len(entries), batch_no))
    except Exception as ex:
        conn.rollback()
        print("  ERROR: %s" % ex)
        raise
    finally:
        conn.close()

    # Verify
    conn2 = sqlite3.connect(DB_PATH)
    count = conn2.execute(
        "SELECT COUNT(*) FROM Carousel WHERE batch_no = ? AND current_stage = 'CATEGORIZED'",
        (batch_no,)
    ).fetchone()[0]
    conn2.close()
    print("  Verified: %d rows with batch_no=%d and current_stage=CATEGORIZED" % (count, batch_no))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", type=int, required=True, help="Batch number")
    parser.add_argument("--categories-file", required=True, help="Path to categories.json")
    parser.add_argument("--dry-run", action="store_true", help="Validate without writing to DB")
    args = parser.parse_args()
    run(args.batch, args.categories_file, args.dry_run)


if __name__ == "__main__":
    main()
