"""
step5_script_writer.py
Validates and inserts carousel scripts generated by the Step 5 agent.

Usage:
  python3 Carousels/scripts/step5_script_writer.py --batch 1 --scripts-file Carousels/data/batch_1/scripts.json
  python3 Carousels/scripts/step5_script_writer.py --batch 1 --scripts-file Carousels/data/batch_1/scripts.json --dry-run
"""

import sqlite3
import os
import json
import argparse

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "db.sqlite")

SLIDE_MIN = 8
SLIDE_MAX = 12
SENTENCE_MAX_WORDS = 20


def _sentences(script):
    return [s.strip() for s in script.split("\n") if s.strip()]


def validate(entries, batch_uuids):
    errors = []

    if len(entries) != 100:
        errors.append("  Expected 100 entries, got %d" % len(entries))

    seen_uuids = set()

    for i, e in enumerate(entries):
        if "uuid" not in e or "script" not in e:
            errors.append("  Entry %d: missing 'uuid' or 'script'" % (i + 1))
            continue

        uid = e["uuid"]
        script = e["script"]

        if uid in seen_uuids:
            errors.append("  Duplicate UUID: %s" % uid)
        seen_uuids.add(uid)

        if uid not in batch_uuids:
            errors.append("  UUID not in batch: %s" % uid)

        sentences = _sentences(script)
        n = len(sentences)

        if not (SLIDE_MIN <= n <= SLIDE_MAX):
            errors.append(
                "  UUID %s: %d sentences (expected %d-%d)" % (uid, n, SLIDE_MIN, SLIDE_MAX)
            )

        for j, s in enumerate(sentences, 1):
            wc = len(s.split())
            if wc > SENTENCE_MAX_WORDS:
                errors.append(
                    "  UUID %s slide %d: %d words (max %d): \"%s\"" % (
                        uid, j, wc, SENTENCE_MAX_WORDS, s,
                    )
                )
            if s.startswith("I ") or s.lower().startswith("my "):
                errors.append(
                    "  UUID %s slide %d: starts with 'I'/'My': \"%s\"" % (uid, j, s)
                )

    return errors


def run(batch_no, scripts_file, dry_run):
    if not os.path.exists(scripts_file):
        print("ERROR: file not found: %s" % scripts_file)
        return

    with open(scripts_file, "r", encoding="utf-8") as f:
        entries = json.load(f)

    print("\n  Loaded %d entries from %s" % (len(entries), scripts_file))

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row

    batch_uuids = {
        r["uuid"]
        for r in conn.execute(
            "SELECT uuid FROM Carousel WHERE batch_no = ? AND current_stage = 'HOOK_WRITTEN'",
            (batch_no,),
        ).fetchall()
    }
    print("  Found %d HOOK_WRITTEN rows for batch %d" % (len(batch_uuids), batch_no))

    errors = validate(entries, batch_uuids)
    if errors:
        print("\n  VALIDATION ERRORS (%d):" % len(errors))
        for e in errors:
            print(e)
        print("\n  Fix scripts.json and re-run.\n")
        conn.close()
        return

    sep = "-" * 72
    print("\n%s\n  Script Preview — Batch %d\n%s" % (sep, batch_no, sep))

    rn_map = {
        r["uuid"]: (r["running_no"], r["title"])
        for r in conn.execute(
            "SELECT uuid, running_no, title FROM Carousel WHERE batch_no = ?", (batch_no,)
        ).fetchall()
    }
    sorted_entries = sorted(entries, key=lambda e: rn_map.get(e["uuid"], (9999, ""))[0])

    for e in sorted_entries:
        uid = e["uuid"]
        rn, title = rn_map.get(uid, ("?", "?"))
        sentences = _sentences(e["script"])
        print("\n  #%-3s (%d slides)  %s" % (rn, len(sentences), title))
        for j, s in enumerate(sentences, 1):
            print("        %2d. %s" % (j, s))
    print("\n" + sep)

    if dry_run:
        print("\n  DRY RUN — no changes made.\n")
        conn.close()
        return

    try:
        conn.execute("BEGIN")
        for e in entries:
            conn.execute(
                "UPDATE Carousel SET script_content = ?, current_stage = 'SCRIPT_WRITTEN' "
                "WHERE uuid = ? AND batch_no = ?",
                (e["script"].strip(), e["uuid"], batch_no),
            )
        conn.commit()
        print("\n  Updated %d rows to SCRIPT_WRITTEN for batch %d\n" % (len(entries), batch_no))
    except Exception as exc:
        conn.rollback()
        print("  ERROR: %s" % exc)
        raise
    finally:
        conn.close()

    conn2 = sqlite3.connect(DB_PATH)
    n = conn2.execute(
        "SELECT COUNT(*) FROM Carousel WHERE batch_no = ? AND current_stage = 'SCRIPT_WRITTEN'",
        (batch_no,),
    ).fetchone()[0]
    conn2.close()
    print("  Verified: %d rows with current_stage = SCRIPT_WRITTEN\n" % n)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--batch", type=int, required=True)
    p.add_argument("--scripts-file", required=True)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()
    run(args.batch, args.scripts_file, args.dry_run)


if __name__ == "__main__":
    main()
